apiVersion: v1
kind: Secret

metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: git
  url: git@github.com:DeboraSerra/Rocketseat.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDdEAmkROMxcVNmJSGL0L6jGxwaZAUWwzDhFnR7zZ8fXQAAAKCVT2PGlU9j
    xgAAAAtzc2gtZWQyNTUxOQAAACDdEAmkROMxcVNmJSGL0L6jGxwaZAUWwzDhFnR7zZ8fXQ
    AAAEDsCtAH3qCbwOw+DFCmIN+bCwpxJW3KHstchPan4R5jvd0QCaRE4zFxU2YlIYvQvqMb
    HBpkBRbDMOEWdHvNnx9dAAAAGGRlYm9yYS5yLnNlcnJhQGdtYWlsLmNvbQECAwQF
    -----END OPENSSH PRIVATE KEY-----


