replicaCount: 5

image:
  repository: deboraserra/api-journey
  pullPolicy: IfNotPresent
  tag: "1fdd512"
  containerPort: 8080

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  # NodePort ou LoadBalancer criam external ip
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: 
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

#livenessProbe:
#  httpGet:
#    path: /health
#    port: http
#readinessProbe:
#  httpGet:
#    path: /ready
#    port: http

autoscaling:
  enabled: false
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
  # targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
