name: CI

on:
  push:
    branches:
      - nlw-16-dev0ops

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./nlw-16/devops/app-journey
          push: true
          tags: |
            deboraserra/api-journey:${{steps.generate_sha.outputs.sha}}
            deboraserra/api-journey:latest

      - name: Update image helm
        uses: fjogeleit/yaml-update-action@main
        with:
          branch: release
          targetBranch: main
          createPR: true
          valueFile: ./nlw-16/devops/app-journey/deploy
          propertyPath: image.tag
          value: ${{steps.generate_sha.outputs.sha}}
          commitChange: true
          message: "NEW: Updage tag in values helm"
