name: CI

on:
  push:
    branches:
      - nlw-16-dev0ops

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t deboraserra/api-journey:${{steps.generate_sha.outputs.sha}} ./nlw-16/devops/app-journey

      - name: Push image
        run: |
          docker push deboraserra/api-journey:${{steps.generate_sha.outputs.sha}}
          docker tag deboraserra/api-journey:${{steps.generate_sha.outputs.sha}} deboraserra/api-journey:latest
          docker push deboraserra/api-journey:latest

